# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-08 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='block_type',
        ),
    ]
