# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-08 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_contentblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='column',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
