# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-09 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_contentblock_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='content_delta',
            field=models.TextField(blank=True),
        ),
    ]
