# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-09 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_contentblock_content_delta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([]),
        ),
    ]
